server:
  port: 8088

eureka:
  client:
    fetch-registry: true
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: msvc-control-obras
          uri: lb://msvc-control-obras
          predicates:
            - Path=/api/control-obras/**

        - id: msvc-equipos-maquinaria
          uri: lb://msvc-equipos-maquinaria
          predicates:
            - Path=/api/equipos-maquinaria/**

        - id: msvc-documentos-obra
          uri: lb://msvc-documentos-obra
          predicates:
            - Path=/api/documentos-obra/**

        - id: msvc-evidencias
          uri: lb://msvc-evidencias
          predicates:
            - Path=/api/evidencias/**

        - id: msvc-proveedores
          uri: lb://msvc-proveedores
          predicates:
            - Path=/api/proveedores/**