server:
  port: 8088

eureka:
  client:
    fetch-registry: true
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders:
              - "*"
            exposedHeaders:
              - Authorization
              - Content-Disposition
            allowCredentials: true
            maxAge: 3600

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

      routes:
        - id: msvc-work-control
          uri: lb://msvc-work-control
          predicates:
            - Path=/api/work-control/**

        - id: msvc-equipos-maquinaria
          uri: lb://msvc-equipos-maquinaria
          predicates:
            - Path=/api/equipos-maquinaria/**

        - id: msvc-documentos-obra
          uri: lb://msvc-documentos-obra
          predicates:
            - Path=/api/documentos-obra/**

        - id: msvc-evidencias
          uri: lb://msvc-evidencias
          predicates:
            - Path=/api/evidencias/**

        - id: msvc-proveedores
          uri: lb://msvc-proveedores
          predicates:
            - Path=/api/proveedores/**

        - id: msvc-usuarios-obra
          uri: lb://msvc-usuarios-obra
          predicates:
            - Path=/api/usuarios-obra/**

        - id: msvc-notificaciones-obra
          uri: lb://msvc-notificaciones-obra
          predicates:
            - Path=/api/notificaciones-obra/**

        - id: msvc-reportes-obra
          uri: lb://msvc-reportes-obra
          predicates:
            - Path=/api/reportes-obra/**

        - id: msvc-catalogos-obra
          uri: lb://msvc-catalogos-obra
          predicates:
            - Path=/api/catalogos-obra/**