version: '3'
services:
  srv_system_gateway:
    build:
      context: ../  # Contexto del build, cambia a la carpeta system-gateway
      dockerfile: Docker/Dockerfile
    restart: always
    container_name: msvc_system_gateway
    ports:
      - "8088:8088"
    volumes:
      - ../build/libs:/home
