version: '3.8'
services:
  srv_system_gateway:
    build:
      context: ../  # Contexto del build, cambia a la carpeta system-gateway
      dockerfile: Docker/Dockerfile
    container_name: msvc_system_gateway
    security_opt:
      - apparmor:unconfined
      - seccomp:unconfined
    ports:
      - "8088:8088"
    restart: always
    deploy:
      resources:
        limits:
          memory: 1024M
          cpus: 0.5
        reservations:
          memory: 1024M
          cpus: 0.5
    networks:
      - docker_default

networks:
  docker_default:
    external: true

