package com.system.modules.controlobras.contracts;

public enum BusFlow {
    BOX_TYPE, BUS_FLOW_ENTER, INDEX_APLICATION_TYPE, BLOCKING_REASONS, CONDITIONED_DOCK, FIXED_APPOINTMENTS,
    DELIVERY_CENTER, TIPOS_DE_CAJA, TURNOS_CENTRO_DE_ENTREGA, TURNOS_TIEMPOS_DE_DESCARGA, TURNOS_CITAS_FIJAS,
    TURNOS_MUELLES_CONDICIONADOS, TURNOS_RAZONES_DE_BLOQUEO, RELATE_APLICATION_TYPE, XML_EVENTS, ATTACHED_DOCUMENT,
    ATTACHED_DOCUMENT_UNSIGNED, JSON_EVENTS, ATTACHED_DOCUMENT_SIGNED, PROCESS_FINISH, UNDEFINED
}